version: '3.8'

services:
  config1:
    image: mongo:5.0
    container_name: config1
    command: mongod --configsvr --replSet configReplSet --port 27017 --dbpath /data/db --bind_ip_all
    ports:
      - 10001:27017
    volumes:
      - config1:/data/db
    networks:
      - mongo-cluster

  config2:
    image: mongo:5.0
    container_name: config2
    command: mongod --configsvr --replSet configReplSet --port 27017 --dbpath /data/db --bind_ip_all
    ports:
      - 10002:27017
    volumes:
      - config2:/data/db
    networks:
      - mongo-cluster

  config3:
    image: mongo:5.0
    container_name: config3
    command: mongod --configsvr --replSet configReplSet --port 27017 --dbpath /data/db --bind_ip_all
    ports:
      - 10003:27017
    volumes:
      - config3:/data/db
    networks:
      - mongo-cluster

  shard1:
    image: mongo:5.0
    container_name: shard1-1
    command: mongod --shardsvr --replSet shard1ReplSet --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - shard1:/data/db
    ports:
      - 50001:27017
    depends_on:
      - config1
      - config2
      - config3
    networks:
      - mongo-cluster

  shard2:
    image: mongo:5.0
    container_name: shard2-1
    command: mongod --shardsvr --replSet shard2ReplSet --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - shard2:/data/db
    ports:
      - 50002:27017
    depends_on:
      - config1
      - config2
      - config3
    networks:
      - mongo-cluster

  shard3:
    image: mongo:5.0
    container_name: shard3-1
    command: mongod --shardsvr --replSet shard3ReplSet --port 27017 --dbpath /data/db --bind_ip_all
    volumes:
      - shard3:/data/db
    ports:
      - 50003:27017
    depends_on:
      - config1
      - config2
      - config3
    networks:
      - mongo-cluster

  mongos:
    image: mongo:5.0
    container_name: mongos
    command: mongos --configdb configReplSet/config1:27017,config2:27017,config3:27017 --bind_ip_all
    depends_on:
      - config1
      - config2
      - config3
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster

volumes:
  config1:
  config2:
  config3:
  shard1:
  shard2:
  shard3:

networks:
  mongo-cluster:
    driver: bridge